In [4]:
import torch
print(torch.cuda.is_available())

True


In [42]:
asdf=torch.tensor([1,2,3,4,5])



In [43]:
asdf=asdf*2
asdf
asdf2=asdf.unsqueeze(1)


In [44]:
print(asdf)
print(asdf2)
print(asdf.shape)
print(asdf2.shape)


tensor([ 2,  4,  6,  8, 10])
tensor([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10]])
torch.Size([5])
torch.Size([5, 1])


In [46]:
asdf2.reshape([-1])


tensor([ 2,  4,  6,  8, 10])

In [18]:
asdf

tensor([[1, 2, 3],
        [3, 4, 3]])

321321654

# 45654

